web: daphne -b 0.0.0.0 -p $PORT Terrabia.asgi:application --verbosity 2
worker: python manage.py runworker --threads 4
release: python manage.py migrate --noinput && python manage.py collectstatic --noinput
